### ISSUE TITLE
Need to create a mini guide for contributors

### ISSUE THREAD

**Issue by AstroWa3l** [armada-alliance/docs#1]
Since we have slightly different syntax in these docs vs contributing on gitbook docs. It can be pretty simple and just give links for more information to docusarus documentation.

**Comment by rekuenkdr** [comment]
@AstroWa3l The docusaurus markdown and styling guide is already linked on the readme (Creating a Doc section), we can extend that section or create a separate md file for contributing with a longer explanation and links, but I think is best to directly point to Docusaurus docs and don't repeat the same content here.

[Docusaurus Markdown and Components Guide](https://docusaurus.io/docs/markdown-features)

**Comment by AstroWa3l** [comment]
That is what I was thinking as well...it's not like we need to do much maybe just highlight some basic "guidelines" then point them to the docs as you said.

**Comment by rekuenkdr** [comment]
This commit [7d2d72e](https://github.com/armada-alliance/docs/commit/7d2d72e133367d47fcc71bba711995837eede677) Should be enough for now.
