### ISSUE TITLE
Update rasp pi ergo-node does to flash and boot directly from external memory

### ISSUE THREAD

**Issue by TheStophe** [armada-alliance/docs#13]
Ran into an issue where the instructions have you flash and boot from the SD Card. The rpi will eventually freeze because the SD Card Memory will overload from RAM and logs. 

An improvement was suggested and tested to flash and boot directly from the external USB memory storage.

This is not only simpler, it works well too after 3 weeks of running.

**Comment by AstroWa3l** [comment]
Yeah, that is what I do on my own rpi's. Should be easy to fix the guides/update them for that method

**Comment by TheStophe** [comment]
I'll make the following updates and open a new pull request:

https://github.com/ccgarant/ergo-full-node-raspi/commit/67319297b57ab79a8ac985cd13c5259962fa3fbf

**Comment by TheStophe** [comment]
Thanks for updating!
