### ISSUE TITLE
error initializing mendable

### ISSUE THREAD

**Issue by AstroWa3l** [armada-alliance/docs#16]
The Docuasuras website/mendable chatbot has not been working. I don't know what the issue is. Everything seems to be correct according to the guide. 

<img width="1457" alt="Screenshot 2024-05-29 at 4 21 31 PM" src="https://github.com/armada-alliance/docs/assets/34224629/8aaaa545-4756-49f1-85c6-3516a0cc5811">

**Comment by AstroWa3l** [comment]
@rekuenkdr I was able to get the issue fixed after reinstalling mendable

**Comment by rekuenkdr** [comment]
> @rekuenkdr I was able to get the issue fixed after reinstalling mendable

It was a problem with the new version of the plugin needing useSyncExternalStore hook that it was introduced on React v18.

I have upgraded the whole Docusaurus to the latest 3.4.0 that also needed React v18.

It should be fixed now. 
[Commit](https://github.com/armada-alliance/docs/commit/732be5830425bb91affa77c7c69feed543e18e58)
[Pipeline](https://github.com/armada-alliance/docs/actions/runs/9420084977/job/25951323807)
