### ISSUE TITLE
Need a search bar

### ISSUE THREAD

**Issue by wcatz** [armada-alliance/docs#3]
Search would be handy to have.

**Comment by rekuenkdr** [comment]
I could implement Algolia, is free for open source projects, we just need to apply:

https://docsearch.algolia.com/apply

Or we can check other community options:

https://docusaurus.io/docs/search

Could you apply to Algolia @AstroWa3l?

Let me know once is done and I'll make the implementation.

**Comment by AstroWa3l** [comment]
Yes, will do it now.

**Comment by AstroWa3l** [comment]
Done, I will close this once I get confirmation we are in

**Comment by rekuenkdr** [comment]
Great!  Thanks!  Leave the issue open until I implement the search functionality, I will close it with the commit.

**Comment by AstroWa3l** [comment]
Sure, I will leave it open. Thanks Daniel

**Comment by AstroWa3l** [comment]
Done. :)
